### PR TITLE
Search label and placeholder should be individually configurable

### PR DESCRIPTION
**Pull request by mejackreed**
Not sure if the `q` value should be kept in for backward compatibility?

### CODE REVIEW

**Comment by cbeer** [comment]
:+1:

**Comment by cbeer** [comment]
Yes, I think we should keep the old key around too, maybe with a comment about being deprecated and removed in 6.0?

**Comment by mejackreed** [comment]
@cbeer added them back in with warning.

**Comment by jrochkind** [comment]
Please do keep the `q` for backwards compatibility.  Is there any reason for `q` not to be default still, even if it's configurable?

When/if `q` is eventually removed, I'll put local code in our app that catches URLs with `q` and redirects them to the new value -- we support bookmarking of search result URLs, and want to make sure existing bookmarked URLs keep working. 

I'd argue for `q` to continue to be the default parameter name, for this reason for all existing BL installs.  But if it's changed I can put in a local redirect.

**Comment by jrochkind** [comment]
Ah wait, ti's just i18n key that's changing, the default URL parameter will still be `q`? Okay, cool, all good!

**Pull request merged**
