### PR TITLE
Prevent checkbox from double rendering

### PR DESCRIPTION
**Pull request by jcoyne**
Previously the use of turbo causes the transformed html to be cached. This causes duplicate checkboxes to appear when returning to a cached page. Here we switch to a server rendered component to prevent the transformation step.

fixes https://github.com/projectblacklight/blacklight/issues/2860

### CODE REVIEW

**Comment by cbeer** [comment]
Doesn't this prevent non-javascript users from being able to use bookmarks? I thought the current approach was intended to  support progressive enhancement.

**Comment by jcoyne** [comment]
Yes, this would prevent non-js users from using bookmarks, however there is a major trade-off in terms of complexity.  We don't know if there are any users who want to use bookmarks without JS. This allows us to remove 150 lines of code and fixes a bug for the existing majority of users.

**Comment by cbeer** [comment]
I guess I don't understand why we can't just make the checkbox conversion idempotent:

https://github.com/projectblacklight/blacklight/pull/2908

**Comment by jcoyne** [comment]
@cbeer that fixes one problem, but the other problem is that dynamic actions that add bookmarks to the page are not handled.

**Pull request closed without merging**
