### PR TITLE
Drop support for ruby 1.9

### LINKED ISSUE #878: Drop support for Ruby 1.9
There are at least a couple places where we're explicitly maintaining compatibility with Ruby 1.9 and 2.0, e.g:

- https://github.com/projectblacklight/blacklight/blob/master/lib/blacklight/utils.rb#L8
- ?
- ?

I suspect there are other places where we could take advantage of Ruby 2.x+ features.

- ? 
- ?
- ?

### PR DESCRIPTION
**Pull request by cjcolvar**
Fixes #878

### CODE REVIEW

**Comment by cbeer** [comment]
Also remove 1.9 from the travis build?

**Comment by mejackreed** [comment]
So.. looks like this might be blocked by a jruby 9000 release.

**Comment by mejackreed** [comment]
Also can you set jruby to allow fails?

```
matrix:
  include:
    - rvm: 2.2.2
      env: "RAILS_VERSION=4.0.12"
    - rvm: 2.2.2
      env: "RAILS_VERSION=4.1.9"
    - rvm: 2.1.6
      env: "RAILS_VERSION=4.2.1"
  allow_failures:
    - rvm: jruby
      env: "RAILS_VERSION=4.2.1 JRUBY_OPTS=\"-J-Xms512m -J-Xmx1024m\""
```

**Comment by jrochkind** [comment]
I believe this change actually STOPPED running CI on Jruby at all. As far as I can tell, a JRuby job was not included in any recent CI, probably since this commit. 

Additionally the desire to allow JRuby to fail (but still run it) until Jruby 9k came out, not sure what motivated that desire in the first place -- but Jruby 9k is out.

**Pull request merged**
