### PR TITLE
Add Albanian (sq) file to locales

### PR DESCRIPTION
**Pull request by dardanll**
Added 'blacklight.sq.yml' Albanian translation file to config/locales

### CODE REVIEW

**Comment by jcoyne** [comment]
It appears to also have this problem on line 64. You can validate the file by pasting it into: http://www.yamllint.com/

**Comment by dardanll** [comment]
@jcoyne Thanks for your help

**Comment by dardanll** [comment]
@jcoyne Please check it

**Comment by cbeer** [comment]
Thanks @dardanll.

**Comment by cbeer** [comment]
@dardanll I've updated our demo.projectblacklight.org site to include these translations. If you get a chance, would you mind localizing these strings too: https://github.com/projectblacklight/demo.projectblacklight.org/blob/master/config/locales/en.yml

**Comment by dhurimkelmendi** [comment]
@cbeer I can translate the demo.projectblacklight.org locales to Albanian if that's not done yet?!

**Pull request merged**
