### PR TITLE
Update compatability in the readme

### PR DESCRIPTION
**Pull request by jcoyne**

### CODE REVIEW

**Review by tampakis — APPROVED** [review]
Approved during community call 7/17/24.

**Comment by jrochkind** [comment]
I hadn't heard of "Baseline 2023" before, but looking into it, it seems like currently the Baseline project defines two points, "newly available" and "widely available". 

https://web.dev/blog/baseline-definition-update

https://developer.mozilla.org/en-US/blog/baseline-evolution-on-mdn/

Are we targetting "newly available 2023" or "widely available 2023"?

**Comment by jcoyne** [comment]
> All items that become part of Baseline Newly Available in 2023 can be referred to as Baseline 2023

 From https://web.dev/baseline
 
 
 So the features we depend on are enumerated here:  https://web.dev/baseline/2023

**Comment by jrochkind** [comment]
OK thanks! I'm learning about this. 

So someone using an old version of say Chrome from say 6 months before 2023 (say on an old ChromeBook that can't update) will not necessarily find Blacklight works for them. OK!

**Pull request merged**
