### PR TITLE
Use RSolr.solr_escape in place of ::escape

### PR DESCRIPTION
**Pull request by awead**
Avoids deprecation warning in RSolr.

### CODE REVIEW

**Comment by cbeer** [comment]
@awead you'll also have to update the gemspec to require that newer version of RSolr. I'm curious why the method name changed, if it is still performing the same task..

**Comment by awead** [comment]
@cbeer I updated the gemspec and also altered the tests that were failing to illustrate the issue. I don't know if `1.11` versus `1\\.11` is significant. It seemed significant when I tried it out in some searches. A possible solution would be to use a local method of escaping that calls the RSolr method and then adds escaped floats. This is similar to what I did in projecthydra/active_fedora#722

**Comment by cbeer** [comment]
Is it significant in a way that rsolr/rsolr should fix, or just different?

**Comment by awead** [comment]
@cbeer I don't know the use case the Blacklight is trying to solve with float. However, the decimal point is not listed as an escaped special character: http://lucene.apache.org/core/4_0_0/queryparser/org/apache/lucene/queryparser/classic/package-summary.html
So, I would say that rsolr/rsolr should keep in line with Lucene and that we should amend Blacklight to address the use case, or either revisit the use case altogether.

**Comment by cbeer** [comment]
What were some of the differences you saw? I'm not sure I have any solr data with floats..

**Comment by awead** [comment]
@cbeer just that I seemed to get search results with an escaped decimal, and did not otherwise. This was using the solr data in the blacklight test suite, which I don't think is a good example. I don't think you have any solr data with floats either.

**Comment by awead** [comment]
@cbeer I ran a test with a document:
`{ "title_t" => "1.11" }`
with the following search:
```
Blacklight.solr.get "select", params: { q: "1.11" }
```
It retrieves the document, so it looks like escaping decimal points in floats in unnecessary. This PR reflects that change in the tests.

**Comment by jcoyne** [comment]
@awead update the gemspec and we can merge this.

**Comment by awead** [comment]
@jcoyne it's `"~> 1.0.6"` right now. Do you want it changed to `"~> 1.0.11"` ?

**Comment by cbeer** [comment]
Or can we support either version with a little cleverness?

**Comment by jcoyne** [comment]
@awead that's what I was suggesting.

**Comment by awead** [comment]
@jcoyne It's a breaking change in RSolr, I think, so it would go to 2.0. `">= 1.0.6"` then?

**Comment by jcoyne** [comment]
@awead Just change this line:
https://github.com/projectblacklight/blacklight/blob/master/blacklight.gemspec#L23

to ` ~> 1.0.11` I don't know why you think that would be a breaking change. We're just updating our dependencies. What is broken?

**Comment by awead** [comment]
@jcoyne ok done. I was over-thinking it.  I thought you wanted to support RSolr 1 and 2, when it came out because the deprecated method would mean a breaking change.

**Comment by jcoyne** [comment]
@awead Great. (FWIW there is no RSolr 2).

**Pull request merged**
