### PR TITLE
Enable building css so that you can run blacklight without sass

### LINKED ISSUE #3206: Enable running blacklight without Sass
With bootstrap 5.2+, it is possible to use CSS variables to customize much of bootstrap, without having to install Sass (and a javascript runtime). This will make it easier for new adopters as they only need to provision a Ruby environment.

### PR DESCRIPTION
**Pull request by jcoyne**
Fixes #3206

### CODE REVIEW

**Comment by jrochkind** [comment]
I'm trying to follow why it requires a new `build.css` css file, what made the previous top-level CSS file not buildable?

**Comment by jcoyne** [comment]
@jrochkind the `build.css` is needed so that we have an entrypoint to build from within the gem.  In the past we've used application.scss within the host application as the entrypoint.

**Comment by jrochkind** [comment]
Thanks @jcoyne

You building on gem release, then? 

I had missed that, I had imagined it was building on assets:precompile for the app.  Did I have it wrong, you are choosing to build on gem release and bundle built css with released gem?

**Comment by jcoyne** [comment]
@jrochkind Yes, the idea here is that we ship precompiled CSS so that the user doesn't need to install Sass (unless they want to).  This should make it easier for new adopters as they don't need to worry about any node dependencies.

**Review by bess — APPROVED** [review]

**Review by bess — APPROVED** [review]

**Pull request merged**
