### PR TITLE
Move base views into the shared directory

### PR DESCRIPTION
**Pull request by jcoyne**

### CODE REVIEW

**Comment by cbeer** [comment]
I can't think of an easy way to deprecate this in 6.x, can you? I figure there's enough other view + css changes that it won't be a big deal just to do it and document it in the release notes.

**Comment by mejackreed** [comment]
Curious about the reasoning here... purely organizational?

**Comment by cbeer** [comment]
Yep; someone noted this at the summit today.

**Comment by mejackreed** [comment]
Great, is there a place where we are collecting breaking changes for the 7.0 release notes?

**Comment by cbeer** [comment]
Not yet; I'll toss a `breaking-change` label on it to remind us later.

**Pull request merged**
