### PR TITLE
Rename scss files to remove extra ".css"

### PR DESCRIPTION
**Pull request by atz**
Example warning:

```
DEPRECATION WARNING: Extra .css in SCSS file is unnecessary. Rename
.../app/assets/stylesheets/blacklight/_modal.css.scss
to
.../app/assets/stylesheets/blacklight/_modal.scss
```

### CODE REVIEW

**Comment by cbeer** [comment]
I think a rebase will fix the failures, right?

**Comment by atz** [comment]
I don't think so.  `release-4.7` branch wasn't successfully building anyway.  (Obviously we're not rebasing a release branch.)  

https://travis-ci.org/projectblacklight/blacklight/builds/170552437

Not sure how you started merging stuff to this branch that had been deleted until this morning.

**Comment by cbeer** [comment]
Hm. I thought I saw a green build. Maybe travis was lagging again.

**Comment by atz** [comment]
Last green was 2 years ago.  Pretty sure if I re-run that, it'll fail.

**Comment by atz** [comment]
@cbeer indeed the old build is now broken, too:
https://travis-ci.org/projectblacklight/blacklight/builds/24069948

**Pull request merged**
