### PR TITLE
do not add nil query value clauses to json query (#3048)

### LINKED ISSUE #3048: Removing a fielded search for a search field with clause params builds invalid JSON queries
**Error:** `Blacklight::Solr::SearchBuilderBehavior#add_search_field_with_json_query_parameters` builds invalid JSON queries when a search field has been specified but all constraint values have been removed
**Steps to reproduce:**
1. Configure clause_params for the title search field
2. Search in the title field
3. Remove the constraint by clicking the 'X' in the results page

Remediation:
The method should either return early if `search_state.query_param` is nil, or default to a blank string if it is falsy

### PR DESCRIPTION
**Pull request by barmintor**
fixes #3048 
This refines the built-in advanced search features and better supports modern Solr

### CODE REVIEW

**Review by jcoyne — CHANGES_REQUESTED** [review]
Can you add a test for this?

**Comment by barmintor** [comment]
rebased on main and pulled in @maxkadel's test (🦖 )

**Comment by barmintor** [comment]
Added a commit to addess rubocop updates:
rubocop-capybara updates change linter rule prefixes; rubocop-rspec updates split 2 linter rules out of `RSpec/FilePath` (now obsolete; one of the excluded files in the latter has been renamed and is no longer problematic.

**Comment by barmintor** [comment]
Added a commit to address kwargs change in selenium-webdriver (#3076 )

**Review by jcoyne — APPROVED** [review]

**Pull request merged**
