### PR TITLE
Resolve "Adding bookmark without bookmark counter raises an error"

### LINKED ISSUE #3214: Adding bookmark without bookmark counter raises an error
Adding/removing a bookmark with the `checkbox_submit` form raises an error when the bookmark counter nav element has not been rendered. This seems to be a previously uncaught javascript error that #3086 has surfaced. 

Steps to reproduce:

- Prevent the `bookmark` `nav_action` from rendering in `CatalogController.configure_blacklight` block
```         
CatalogController.configure_blacklight do |config|
          config.add_nav_action(:bookmark, partial: 'blacklight/nav/bookmark', if: proc { false })
        end
```
- Attempt to add a bookmark on search results page using the "Bookmark" checkbox 
- View alert prompt that says "Unable to save the bookmark at this time."
  - note: the bookmark is actually saved/destroyed despite the alert

Proposed solution:
 - In  the `CheckboxSubmit` javascript component, we can verify the bookmark counter exists before incrementing the count.

### PR DESCRIPTION
**Pull request by mamrey**
Closes #3214

### CODE REVIEW

**Review by jcoyne — APPROVED** [review]

**Comment by jcoyne** [comment]
@mamrey thank you.

**Comment by mamrey** [comment]
There was a rubocop issue that should be resolved now :)

**Comment by cgalarza** [comment]
We are very interested in getting this fix merged and released so we can update our new Catalog to the newest version of blacklight. Could a maintainer approve the workflow for this MR? I am happy to become a maintainer if that would be helpful!

**Comment by jcoyne** [comment]
Can this be rebased on main? I believe the problem with Ruby 3.2 builds is resolved there.

**Comment by cgalarza** [comment]
Amrey is away on vacation and I don't have access to his fork. He's back on Monday, but if there's another way I could do it, I am happy to.

**Comment by jcoyne** [comment]
@cgalarza you should be able to `git cherry-pick` his commit into your own branch.

**Comment by cgalarza** [comment]
I ran the pipeline in my local fork and there's still an error. I'll have to look at it tomorrow. 

https://github.com/cgalarza/blacklight/pull/2

**Comment by cgalarza** [comment]
@jcoyne I am wondering if you have any advice on how to fix this error. It seems that capybara is not finding the 'Bookmarks' link because of the badge that's included in the link. The test works if I change the problematic line to:
- `click_link 'Bookmarks' `
- `click_on :bookmarks_nav`
- `click_on 'Bookmarks 0'`

The best also passes if I add the `:js` tag to the test.

**Comment by cgalarza** [comment]
Hi @jcoyne, @mamrey and I resolved the testing issue. We've pushed up a change that we believe fixes the problem and have merged in the last changes from `main`.

**Comment by jcoyne** [comment]
@mamrey @cgalarza I've been having a bit of trouble in the BL codebase recently and It keeps coming back to the test from this PR.  I'm especially confused about the stub for `render_bookmarks_control?` as this isn't a controller method:
```
irb(main):001> CatalogController.render_bookmarks_control?
(irb):1:in `<main>': undefined method `render_bookmarks_control?' for class CatalogController (NoMethodError)

CatalogController.render_bookmarks_control?
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^
```

**Comment by jcoyne** [comment]
I removed this test in #3245 to get the build working.

**Comment by mamrey** [comment]
@jcoyne 

Thank you for working on this. Yes, the test depends on the bookmark control not being rendered. The initial spec attempted to achieve this by adding the appropriate blacklight config. When looking into the build failures we found [this test](https://github.com/projectblacklight/blacklight/blob/abf6f24bb8e53354dc91db8520f029bee68c4a4c/spec/helpers/blacklight_helper_spec.rb#L118) that we took inspiration from. I am okay with removing the test as you've done.

**Comment by jcoyne** [comment]
@mamrey the difference is that in https://github.com/projectblacklight/blacklight/blob/abf6f24bb8e53354dc91db8520f029bee68c4a4c/spec/helpers/blacklight_helper_spec.rb#L118 the method is stubbed on the controller instance and in this PR it's stubbed on the class (there is no method on the class).

**Pull request merged**
