### PR TITLE
Stop supporting Rails 6

### LINKED ISSUE #3223: Drop Rails 6 support

### PR DESCRIPTION
**Pull request by jcoyne**
Fixes #3223

### CODE REVIEW

**Comment by jcoyne** [comment]
https://github.com/rails/rails/pull/52471#issuecomment-2271622034

6.1 is EOL October 2024.

**Comment by cgalarza** [comment]
Does the `.env` file need to be updated as well? https://github.com/projectblacklight/blacklight/blob/f55d9b30e36848c8490f0ac7c3b284814bf25091/.env#L2

Does the `.rubocop` configuration need to be updated too? 
https://github.com/projectblacklight/blacklight/blob/f55d9b30e36848c8490f0ac7c3b284814bf25091/.rubocop.yml#L14

**Comment by cgalarza** [comment]
It would also be nice to merge in `main` to make sure this doesn't break any recent additions.

**Comment by jcoyne** [comment]
I made https://github.com/projectblacklight/blacklight/pull/3320 which can go first. It takes care of the Docker deps.

**Review by cgalarza — APPROVED** [review]

**Pull request merged**
