### PR TITLE
Stop testing on ruby 2.6

### PR DESCRIPTION
**Pull request by jcoyne**
Ruby 2.6 is no longer supported. It no longer receives security updates.  https://www.ruby-lang.org/en/news/2021/11/24/ruby-2-6-9-released/

### CODE REVIEW

**Comment by cbeer** [comment]
Should we also bump https://github.com/projectblacklight/blacklight/blob/main/blacklight.gemspec#L26?

**Comment by cbeer** [comment]
Should we also bump https://github.com/projectblacklight/blacklight/blob/main/blacklight.gemspec#L26?

**Comment by jcoyne** [comment]
I think that makes sense. Then we can use new language features.

**Review by barmintor — APPROVED** [review]
gemspec: check
testing matrix: check
AllCops/TargetRubyVersion: check
👍

**Pull request merged**
