### PR TITLE
Use the new slot API for the modal

### LINKED ISSUE #3102: Unsupported ViewComponent slots in SMS and Email tools
The gemspec for Blacklight specifies a version of ViewComponent that is `'>= 2.66', '< 4'`. In my project, with ViewComponent 3.0, the SMS and Email tools were not rendering correctly. Per the [ViewComponent changelog](https://viewcomponent.org/CHANGELOG.html#300rc1), ViewComponent 3.0 contains the following breaking changes:
- BREAKING: Remove deprecated slots setter methods. Use with_SLOT_NAME instead.
- BREAKING: Remove deprecated SlotsV1 in favor of current SlotsV2.

The SMS and Email tools are still rendered using the deprecated setter methods. Here's the SMS code for example:
```erb
<%= render Blacklight::System::ModalComponent.new do |component| %>
  <% component.title { t('blacklight.sms.form.title') } %>

  <% component.body do %>
    <%= render 'sms_form' %>
  <% end %>
<% end %>
```
This code can be fixed by updating it to the following:
```erb
<%= render Blacklight::System::ModalComponent.new do |component| %>
  <% component.with_title { t('blacklight.sms.form.title') } %>

  <% component.with_body do %>
    <%= render 'sms_form' %>
  <% end %>
<% end %>
```
The alternative solution is to limit the ViewComponent version to something < 3.0, but it seems like transition to the newer setter methods has been started.

### PR DESCRIPTION
**Pull request by jcoyne**
Closes #3102 and #3106

### CODE REVIEW

**Comment by jrochkind** [comment]
Oops, needed to actually work with ViewComponent 3.x, so a bug fix, yes?

**Comment by jcoyne** [comment]
@jrochkind yes, this is largely the same as https://github.com/projectblacklight/blacklight/pull/3106 but with the build passing (mostly)

**Comment by jrochkind** [comment]
Thanks! The difference between #3106 and this seems to be this one lacks additional specs.  

Since the tests are being run with ViewComponent 3.x (yes?), which this func definitely doesn't work with... the fact that we had green builds WITHOUT fixing #3102 definitely suggests we are missing some test coverage.  So ideally we would add test coverage that would be red without this fix. 

But if it's infeasible to provide for some reason, I guess better to have a fix that isn't covered by a test than no fix at all, I could approve anyway if it's infeasible to cover with test.

**Comment by jcoyne** [comment]
@jrochkind I've added some tests here.

**Review by jrochkind — APPROVED** [review]

**Comment by jrochkind** [comment]
Curious why #3106 didn't pass, where it differed, but approved!

**Pull request merged**
