### PR TITLE
Encapsulate the blacklight config

### PR DESCRIPTION
**Pull request by jcoyne**
All values set on Blacklight::Engine.config are actually stored
in a class variable on Railtie::Configuration. So these pollute
that namespace.  All other railties are encapsulating their configs
onto a single entry in that scope.  This change makes Blacklight do
likewise.

This probably needs to be a major revision

### CODE REVIEW

**Comment by bess** [comment]
+1 but it seems like we should talk about when to merge this, if we think it's a major version increment. Would it make sense to mark this as a Blacklight 8 feature?

**Comment by barmintor** [comment]
Now that the 8.0.0.alpha tag is in [main](https://github.com/projectblacklight/blacklight/commit/a82e70484ba89ea84380a213dee89c3cbd3acb95), can we revive this PR?

**Comment by barmintor** [comment]
Rebasing for CI before merge.

**Comment by barmintor** [comment]
The OpenStruct linter rule was added in the interim of this PR being opened. There's three approaches available to us:

1. Use OpenStructWithHashAccess here, and remove it (or not) along with the rest of the usages of that class
2. Add to `rubocop_todo`
3. Disable the `Style/OpenStructUse` linter rule.

I think there's an argument for disabling the rule rather than adding yet another `todo`, but I'm also sympathetic to using OpenStructWithHashAccess and dealing with that (or not!) as a single task in the future.

**Comment by tpendragon** [comment]
https://github.com/rubocop/rubocop/issues/10206 is where they added this, and it makes a good point that Ruby 3 basically says "quit it."

I'm for option 1, and actually removing that class one day (although I suspect it's gonna be hard :( )

**Comment by barmintor** [comment]
Sold @tpendragon. I'll merge after CI.

**Comment by cbeer** [comment]
@jcoyne  or @barmintor, can you create a PR against the release-7.x with appropriate deprecations and a migration path for this change?

**Comment by jcoyne** [comment]
@cbeer I wouldn't know how to do that as `Blacklight::Engine.config` is pointing at the `Railtie::Configuration`. Since that's not a class we control, we can't add deprecations to it.

**Comment by barmintor** [comment]
It's true that it might be awkward, but I created https://github.com/projectblacklight/blacklight/issues/2607 to try to work through it @cbeer

**Comment by barmintor** [comment]
Ok, I have a proposed deprecation up in https://github.com/projectblacklight/blacklight/pull/2610

Spoiler: It _was_ kind of awkward.

**Pull request merged**
