### PR TITLE
update for Rubocop 0.48

### PR DESCRIPTION
**Pull request by dunn**
Trying #1650 again.

### CODE REVIEW

**Comment by jcoyne** [comment]
@dunn you'll need to unpin rubocop in the gemspec too.

**Comment by dunn** [comment]
🎊

**Comment by dunn** [comment]
Would someone mind merging this? Rebasing it can be a bit tricky.

**Comment by jcoyne** [comment]
@dunn is there a reason you closed this? We were planning on merging this as one of the very last PRs before 7, because style changes always make backports tricky.

**Comment by dunn** [comment]
@jcoyne sorry, I just got this notification.

It had fallen out of date again and I'd gotten no indication that it was going to be merged, so I tossed it.  I can open a new PR when 7 is nearly done, or feel free to cherry-pick anything still applicable if you'd like to push it across the finish line.

**Pull request closed without merging**
