### PR TITLE
Group facets into separate blocks based upon group specified on facet field in config

### LINKED ISSUE #704: Grouping of facet fields
e.g. librarian facets vs patron facets

screen shot 2014-01-24 at 11 44 55

### PR DESCRIPTION
**Pull request by cjcolvar**
Fixes #704.

### CODE REVIEW

**Comment by cbeer** [comment]
I see a lot of similarities with #1417. I wonder if we can come up with a consistent approach for this kind of configuration grouping?

**Comment by barmintor** [comment]
This is something that can be dealt with in a feature release, right?

**Comment by cjcolvar** [comment]
@barmintor @cbeer I rebased this for kicks.  Let me know if there is anything I can do or reworking of this PR that might make it palatable for 7.0.

**Comment by jkeck** [comment]
:shipit:

**Comment by cjcolvar** [comment]
Now I need to upgrade to Blacklight 7 in order to pull in this change and get rid of my local overrides.

**Pull request merged**
