### PR TITLE
[WIP] failing test for #label_for_search_field where no search fields are c…

### PR DESCRIPTION
**Pull request by mejackreed**
…onfigured

This is a failing test (and hopefully at some point a fix) for `label_for_search_field` when no search fields are configured. I'm not sure what the expected behavior should be.

### CODE REVIEW

**Comment by skng5** [comment]
On further examination, this test won't work. We should test for the `Keyword` label. The problem is in `helper.label_for_search_field(nil))` which returns a hash instead of the default `Keyword` label.

**Comment by jkeck** [comment]
@skng5 I think the intention was to have the test fail, and the TODO here is to write the code to make the test pass.  Will let @mejackreed confirm.

**Comment by skng5** [comment]
@mejackreed @jkeck The translation path to the default label is doesn't correspond to anything in the translation file. I've changed it to what we want.

**Comment by skng5** [comment]
Undetermined desired behavior.

**Pull request closed without merging**
