### PR TITLE
Add missing rubocop gems and auto-update

### PR DESCRIPTION
**Pull request by jcoyne**

### CODE REVIEW

**Review by mjgiarlo — APPROVED** [review]

**Comment by jrochkind** [comment]
Any idea what made `be_a_kind_of`, that apparently previously worked, stop working and have to be changed to `be_a`?

**Comment by jcoyne** [comment]
@jrochkind  I think it's just a matter of preference. https://docs.rubocop.org/rubocop-rspec/cops_rspec.html#rspecclasscheck is the rule

**Comment by mjgiarlo** [comment]
@jrochkind 💬 
> Any idea what made `be_a_kind_of`, that apparently previously worked, stop working and have to be changed to `be_a`?
> 
> (The mystery might be why `be_a_kind_of` _ever_ worked! The correct method name, that I think still would be working as a synonum to `be_a`, is `be_kind_of` (no `_a_`))

RSpec allows a bunch of different forms: https://github.com/rspec/rspec-expectations/blob/main/lib/rspec/matchers.rb#L372-L382

**Comment by jrochkind** [comment]
Ah, so it had to be changed in this PR becuase you enabled a rubocop rule that forced it to be changed? Okeydoke!

**Pull request merged**
