### PR TITLE
Move search_service_class to Searchable

### PR DESCRIPTION
**Pull request by jcoyne**
Anything that uses Searchable should be able to configure a search_service_class, this does not have anything to do with a Controller.  This keeps the concept of the search service encapsulated in the Searchable module.

### CODE REVIEW

**Comment by barmintor** [comment]
Is there a reason to wait to do the same thing for the `search_state_class` accessor? It would clean Blacklight::Controller up, and it would be nice to have a single documented external dependency for Blacklight:Searchable. Happy to push a commit doing this if you're pressed for time!

**Comment by barmintor** [comment]
Adding that it doesn't seem to me that there's a _real_ backwards compatibility here - it seems unlikely that an app is using Blacklight::Controller in a context without the Catalog mixin while also using the search_service and search_state machinery, right?

**Comment by barmintor** [comment]
> Is there a reason to wait to do the same thing for the search_state_class accessor?

Yes: the `search_state` accessors are also used by SearchHistoryController, which inherits from ApplicationController and only borrows configuration from CatalogController. That needs to be handled separately.

**Comment by barmintor** [comment]
Rebased before CI.

**Review by barmintor — APPROVED** [review]

**Comment by barmintor** [comment]
There's a bootstrap5 accessibility failure here re: text contrast that is not related to the change (and not a required check). I am merging.

**Comment by jcoyne** [comment]
That test is flappy and is often resolve by rerunning the suite

**Pull request merged**
