### PR TITLE
Allow defining attributes on SolrDocument

### PR DESCRIPTION
**Pull request by jcoyne**

### CODE REVIEW

**Comment by atz** [comment]
What is projected to use this otherwise untapped feature?

**Comment by jcoyne** [comment]
@atz for Hydra.  In conjunction with #1655 we should be able to provide different subclasses of SolrDocument based on the object type field.  This will enable us to avoid one SolrDocument that is the union of all the methods that could appear on any object type.

**Comment by jrochkind** [comment]
If you use the method name `cast` instead of `coerce`, you'll be closer to the Rails5-standard ActiveModel::Type API.  

ActiveModel::Type basic API is actually `cast`, `serialize`, and `deserialize`, although sometimes one or more are defined in terms of the others. 

See "Creating Custom Types" here http://api.rubyonrails.org/classes/ActiveRecord/Attributes/ClassMethods.html (although it's in the context of the more complicated ActiveRecord example, it's based on a simpler ActiveModel::Type context, but this is the best docs). 

As well as: http://api.rubyonrails.org/classes/ActiveModel/Type/Value.html

**Comment by jcoyne** [comment]
@jrochkind I'm using `coerce` as it follows the pattern from `Virtus` rather than `ActiveModel::Type`  https://github.com/solnic/virtus

**Comment by cbeer** [comment]
It seems like it's possible for you to use virtus (or, now, dry-types) directly in your application, no? I'd personally be more comfortable with this after seeing it used somewhere before we push it upstream. I also agree with @jrochkind that aligning closer with the Rails practice may be easier for people to learn about / adopt?

**Comment by jrochkind** [comment]
Actually I would find this useful in the sense of putting things directly in Blacklight actually architecturally clean within Blacklight, instead of things like hyrax having to add them on top. 

I haven't looked at the implementation, and don't have any opinions on it. But the API actually does seem fairly "rails like" to me. In Rails 5.2, ActiveModel::Attributes/ActiveModel::Type has gotten a lot more powerful, and I think it's possible you could do this _just_ with ActiveModel::Attributes -- which would of course be very Rails-like. (I have no idea how you deal with the fact that Blacklight supports older Rails though). 

I actually didn't realize I had commented on this before -- now I see my comment, and do still agree with it, it would be better to stick as close to Rails conventions -- especially with Rails 5.2 giving you a lot of this out of the box, stick to it's conventions -- especially with virtus being essentially abandoned by it's creator at this point, I see no reason to stick to virtus conventions. 

But the _feature_, apart from the API/implementation details, what it's trying to do -- I like a lot.

**Pull request merged**
