### PR TITLE
solving issue #1410

### PR DESCRIPTION
**Pull request by qsebas**
comma misssing in the template catalog_controller.rb

solving
https://github.com/projectblacklight/blacklight/issues/1410

### CODE REVIEW

**Comment by jcoyne** [comment]
Thank you @qsebas!

**Comment by qsebas** [comment]
it's my first commit on a open source project :)

how should close issue #1410?

**Comment by jcoyne** [comment]
I've fixed it.  Typically I write `Fixes #1410` in the commit message of a pull request.  Then when the pull request is merged the ticket is automatically closed.

**Comment by mejackreed** [comment]
Thanks for the contribution @qsebas! 🎆 😆

**Pull request merged**
