### PR TITLE
added Chinese locale (#1806)

### PR DESCRIPTION
**Pull request by mjgiarlo**
Backport #1806 to 6.x release branch. (Thanks, @yuxisteem!)

Also:

* add Chinese translations for keys that were removed in `master`. (HT: @cbeer)
* backport work from https://github.com/projectblacklight/blacklight/pull/1820 to fix the build

### CODE REVIEW

**Comment by cbeer** [comment]
To backport to Blacklight 6, you'll probably want to provide translations for some keys that are being removed in 7:

https://github.com/projectblacklight/blacklight/commit/0d7e962a0e05ce58c205f2fff0d543206242bcef#diff-ad9f93c4468ae38646b8c7c3e32d3546
https://github.com/projectblacklight/blacklight/commit/2f26c6e06f11fefd62bd8f54a1a1f9cc58686118#diff-ad9f93c4468ae38646b8c7c3e32d3546

**Comment by mjgiarlo** [comment]
@cbeer Done. Thanks!

**Comment by jcoyne** [comment]
@mjgiarlo can you squash the last two commits together?

**Comment by mjgiarlo** [comment]
@jcoyne Done.

**Pull request merged**
