### PR TITLE
Remove deprecated method: discard_flash_if_xhr

### PR DESCRIPTION
**Pull request by jgondron**
This discard flash method is beginning to cause problems with todays integration of rails and turbolinks. Ex: https://github.com/samvera/hyrax/issues/2592. Would like to remove this from 7.x. 

Related: #1863

### CODE REVIEW

**Comment by jeremyf** [comment]
@jcoyne Can you restart this job https://travis-ci.org/projectblacklight/blacklight/jobs/364115047

**Comment by jcoyne** [comment]
@jeremyf I restarted the build but it still failed. Perhaps a rebase?

**Comment by jcoyne** [comment]
This also causes an issue with API mode, where there is no flash:
```
NameError (undefined local variable or method `flash' for #<CatalogController:0x00007fa45e014230>):
```

**Comment by jcoyne** [comment]
Rebased into #1896

**Pull request closed without merging**
