### PR TITLE
Demote rsolr to a development dependency

### PR DESCRIPTION
**Pull request by cbeer**

### CODE REVIEW

**Comment by jcoyne** [comment]
Should we remove the `require 'rsolr'` here? https://github.com/projectblacklight/blacklight/blob/d986ca2ccc69011d2fd9f8cd41a46f199b441e23/app/models/concerns/blacklight/solr/document.rb#L2

**Comment by cbeer** [comment]
Hm, good question. If we're assuming rsolr is getting injected upstream, I guess so, right?

**Comment by jcoyne** [comment]
@cbeer that seems reasonable.

**Comment by cbeer** [comment]
@jcoyne: fixed up.

**Pull request merged**
