### PR TITLE
Use resourceful routing

### LINKED ISSUE #1200: CatalogController subclasses don't have access to all their routes by default
We're working on an engine that subclasses the `CatalogController`, and we recently attempted to add "more" links to facets based on a user request. However, when we first enabled it, we got an `ActionView::Template::Error` [(stacktrace here)](https://gist.github.com/anarchivist/6a37894d84d07425e136). 

@terrellt suggested that this was an issue he ran into before, and suggested adding the following workaround in our engine's `config/routes.rb`:

```ruby
Krikri::Engine.routes.draw do
  # ...snip...
  resources :records, only: [:index, :show] do
    collection do
      get "facet/:id", :to => "records#facet"
    end
  end
# ...snip...
end
```

### PR DESCRIPTION
**Pull request by cbeer**
This allows applications to use Rails 4's routing concerns to create Blacklight routes.

Here is an example of parity with existing routes:

```ruby
  concern :searchable, Blacklight::Routes::Searchable.new
  concern :exportable, Blacklight::Routes::Exportable.new

  resource :catalog, only: [:index] do
    concerns :searchable
  end

  resources :solr_documents, only: [:show], controller: 'catalog' do
    concerns :exportable
  end
```

This allows downstream applications to easily use Rails routing to configure their routes, e.g.:

```ruby
  resource :catalog, only: [:index], path: '/view' do
    concerns :searchable
  end

   # search_catalog GET|POST /view(.:format)                   catalogs#index
   # track_catalog POST     /view/:id/track(.:format)         catalogs#track
   # opensearch_catalog GET      /view/opensearch(.:format)        catalogs#opensearch
   # facet_catalog GET      /view/facet/:id(.:format)         catalogs#facet
```

or easily have multiple blacklight catalog controllers:

```ruby
  resource :image_catalog do
    concerns :searchable
  end

  resource :video_catalog do
    concerns :searchable
  end
```

Part of #1218 
Fixes #1200

### CODE REVIEW

**Comment by jcoyne** [comment]
I really like this. :+1:  Needs a rebase though.

**Comment by jkeck** [comment]
:+1: for routing concerns

**Comment by jcoyne** [comment]
... and I merged another PR first, so rebase again.

**Comment by cbeer** [comment]
Rebased. I think the loss of coverage is just removing well-covered lines of code.

**Pull request merged**
