### PR TITLE
Use and prefer view config components by default over the default view config partials

### PR DESCRIPTION
**Pull request by cbeer**
Now that we're enabling and configuring view components enabled by default, we can stop configuring partials by default. Partial configuration is still available and will append the rendered content to the document.

### CODE REVIEW

**Comment by dkinzer** [comment]
I've been playing around with upgrading one of our instances to latest release and it fails with that, but with this branch I'm able to upgrade without issues.

**Comment by cbeer** [comment]
Hm. I wouldn't expect that #2458 would have changed anything. Can you provide more detail about what the issue was? I do think the repurposed partial configuration here will make migration easier (but are difficult to make backwards compatible), so maybe that's it?

**Comment by dkinzer** [comment]
@cbeer the error I getting at fd33c74a378d164a571174fa0054c25b70ef09d1

is 

<header style="color: rgb(240, 240, 240); background: rgb(197, 47, 36); padding: 0.5em 1.5em; font-family: helvetica, verdana, arial, sans-serif; font-size: 13px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><h1 style="margin: 0.2em 0px; line-height: 1.1em; font-size: 2em;">NoMethodError in Catalog#show</h1></header><div id="container" style="box-sizing: border-box; width: 1372px; padding: 0px 1.5em; color: rgb(51, 51, 51); font-family: helvetica, verdana, arial, sans-serif; font-size: 13px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; margin-bottom: 148px;"><p style="font-family: helvetica, verdana, arial, sans-serif; font-size: 13px; line-height: 18px;">Showing<span> </span><i>/Users/dkinzer/projects/funnel_cake/app/views/catalog/_show.html.erb</i><span> </span>where line<span> </span><b>#1</b><span> </span>raised:</p><pre style="font-size: 11px; white-space: pre-wrap;"><code>undefined method `show_presenter' for #&lt;#&lt;Class:0x00007fa748452a58&gt;:0x00007fa748405af0&gt;</code></pre><div class="source " id="frame-source-0" style="border: 1px solid rgb(217, 217, 217); background: rgb(236, 236, 236); width: 978px;"><div class="info" style="margin: 0px; padding: 0.5em;">Extracted source (around line<span> </span><strong style="margin: 0px; padding: 0px;">#1</strong>):</div><div class="data" style="margin: 0px; padding: 0px; font-size: 10.4px; overflow: auto; background-color: rgb(255, 255, 255);">

1 2 3 4 5 6 | <% doc_presenter = show_presenter(document) %>   <%# default partial to display solr document fields in catalog show view -%> <div class="row">   <div class="col-12">
-- | --


</div></div></div><br class="Apple-interchange-newline">

Which happens when I try to look at a document.  If I switch to this branch the issue is resolved.

**Comment by dkinzer** [comment]
Also, we are overriding that template that is failing with this
```
<% doc_presenter = show_presenter(document) %>


<%# default partial to display solr document fields in catalog show view -%>
<div class="row">
  <div class="col-12">
    <dl class="row dl-invert document-metadata">
      <% doc_presenter.fields_to_render.each do |field_name, field| -%>
        <dt class="blacklight-<%= field_name.parameterize %> col-md-3"><%= render_document_show_field_label document, field: field_name %></dt>
        <dd class="align-self-center blacklight-<%= field_name.parameterize %> col-md-9"><%= doc_presenter.field_value field %></dd>
      <% end -%>
    </dl>
  </div>
  <div class="col-12">
    <dl class="row dl-invert document-metadata">
      <dt class="align-self-center col-md-3"><%= staff_view_link(document.id) %></dt>
    </dl>
  </div>
</div>
```

**Comment by jcoyne** [comment]
@dkinzer `show_presenter` was removed from the 8.x (main) branch.  It was deprecated https://github.com/projectblacklight/blacklight/blob/release-7.x/app/helpers/blacklight/blacklight_helper_behavior.rb#L338

**Review by jcoyne — APPROVED** [review]

**Pull request merged**
