### PR TITLE
Fix Dockerfile build error.

### LINKED ISSUE #2264: Getting the following now and the app doesn't run.
Getting the following now and the app doesn't run.

```
ERROR: Service 'app' failed to build: The command '/bin/sh -c wget -qO- https://deb.nodesource.com/setup_9.x | bash - &&       wget -qO- https://dl.yarnpkg.com/debian/pubkey.gpg | apt-key add - &&       echo "deb https://dl.yarnpkg.com/debian/ stable main" | tee /etc/apt/sources.list.d/yarn.list &&       apt-get update -qq &&       apt-get install -y --force-yes --no-install-recommends &&       nodejs yarn build-essential libpq-dev       && apt-get clean' returned a non-zero code: 127
```

Complete log here:

```
➜  blacklight git:(master) docker-compose up
Building app
Step 1/5 : FROM ruby:2.6
 ---> 8f309d9e27ea
Step 2/5 : RUN       wget -qO- https://deb.nodesource.com/setup_9.x | bash - &&       wget -qO- https://dl.yarnpkg.com/debian/pubkey.gpg | apt-key add - &&       echo "deb https://dl.yarnpkg.com/debian/ stable main" | tee /etc/apt/sources.list.d/yarn.list &&       apt-get update -qq &&       apt-get install -y --force-yes --no-install-recommends &&       nodejs yarn build-essential libpq-dev       && apt-get clean
 ---> Running in ffd797a3e1eb

================================================================================
================================================================================

                              DEPRECATION WARNING

  Node.js 9.x is no longer actively supported!

  You will not receive security or critical stability updates for this version.

  You should migrate to a supported version of Node.js as soon as possible.
  Use the installation script that corresponds to the version of Node.js you
  wish to install. e.g.

   * https://deb.nodesource.com/setup_10.x — Node.js 10 LTS "Dubnium" (recommended)
   * https://deb.nodesource.com/setup_12.x — Node.js 12 LTS "Erbium"

  Please see https://github.com/nodejs/Release for details about which
  version may be appropriate for you.

  The NodeSource Node.js distributions repository contains
  information both about supported versions of Node.js and supported Linux
  distributions. To learn more about usage, see the repository:
    https://github.com/nodesource/distributions

================================================================================
================================================================================

Continuing in 20 seconds ...


## Installing the NodeSource Node.js 9.x repo...


## Populating apt-get cache...

+ apt-get update
Get:1 http://security.debian.org/debian-security buster/updates InRelease [65.4 kB]
Get:2 http://deb.debian.org/debian buster InRelease [122 kB]
Get:3 http://deb.debian.org/debian buster-updates InRelease [49.3 kB]
Get:4 http://security.debian.org/debian-security buster/updates/main amd64 Packages [182 kB]
Get:5 http://deb.debian.org/debian buster/main amd64 Packages [7907 kB]
Get:6 http://deb.debian.org/debian buster-updates/main amd64 Packages [7380 B]
Fetched 8332 kB in 2s (4010 kB/s)
Reading package lists...

## Installing packages required for setup: lsb-release...

+ apt-get install -y lsb-release > /dev/null 2>&1

## Confirming "buster" is supported...

+ curl -sLf -o /dev/null 'https://deb.nodesource.com/node_9.x/dists/buster/Release'

## Adding the NodeSource signing key to your keyring...

+ curl -s https://deb.nodesource.com/gpgkey/nodesource.gpg.key | apt-key add -
Warning: apt-key output should not be parsed (stdout is not a terminal)
OK

## Creating apt sources list file for the NodeSource Node.js 9.x repo...

+ echo 'deb https://deb.nodesource.com/node_9.x buster main' > /etc/apt/sources.list.d/nodesource.list
+ echo 'deb-src https://deb.nodesource.com/node_9.x buster main' >> /etc/apt/sources.list.d/nodesource.list

## Running `apt-get update` for you...

+ apt-get update
Hit:1 http://security.debian.org/debian-security buster/updates InRelease
Hit:2 http://deb.debian.org/debian buster InRelease
Hit:3 http://deb.debian.org/debian buster-updates InRelease
Get:4 https://deb.nodesource.com/node_9.x buster InRelease [4622 B]
Get:5 https://deb.nodesource.com/node_9.x buster/main amd64 Packages [765 B]
Fetched 5387 B in 1s (8109 B/s)
Reading package lists...

## Run `sudo apt-get install -y nodejs` to install Node.js 9.x and npm
## You may also need development tools to build native addons:
     sudo apt-get install gcc g++ make
## To install the Yarn package manager, run:
     curl -sL https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add -
     echo "deb https://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
     sudo apt-get update && sudo apt-get install yarn


Warning: apt-key output should not be parsed (stdout is not a terminal)
OK
deb https://dl.yarnpkg.com/debian/ stable main
Reading package lists...
Building dependency tree...
Reading state information...
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
W: --force-yes is deprecated, use one of the options starting with --allow instead.
/bin/sh: 1: nodejs: not found
ERROR: Service 'app' failed to build: The command '/bin/sh -c wget -qO- https://deb.nodesource.com/setup_9.x | bash - &&       wget -qO- https://dl.yarnpkg.com/debian/pubkey.gpg | apt-key add - &&       echo "deb https://dl.yarnpkg.com/debian/ stable main" | tee /etc/apt/sources.list.d/yarn.list &&       apt-get update -qq &&       apt-get install -y --force-yes --no-install-recommends &&       nodejs yarn build-essential libpq-dev       && apt-get clean' returned a non-zero code: 127
```

_Originally posted by @cdmo in https://github.com/projectblacklight/blacklight/pull/2262#issuecomment-598899701_

### PR DESCRIPTION
**Pull request by dkinzer**
Fixes build error do to `&&` being in wrong spot.

Fixes #2264

### CODE REVIEW

**Comment by dkinzer** [comment]
OK, ... still seeing an error though that I didn't used to get before

```
app_1   |
app_1   | Done generating test app
app_1   | rake aborted!
app_1   | NameError: uninitialized constant SolrWrapper
app_1   | tasks/blacklight.rake:56:in `block (2 levels) in <top (required)>'
app_1   | /usr/local/bundle/gems/rake-13.0.0/exe/rake:27:in `<top (required)>'
app_1   | /usr/local/bundle/bin/bundle:23:in `load'
app_1   | /usr/local/bundle/bin/bundle:23:in `<main>'
app_1   | Tasks: TOP => blacklight:server
app_1   | (See full trace by running task with --trace)
blacklight_app_1 exited with code 1
```

🤦‍♂

**Comment by dkinzer** [comment]
OK, was able to get blacklight site up by removing solr_wrapper from Rakefile, and managed to get the blacklight site up on my local:
image

**Comment by cdmo** [comment]
I seem to have run into a different error when I tried this. Log:

[docker-compose-up.log](https://github.com/projectblacklight/blacklight/files/4339898/docker-compose-up.log)


```
<snip>
app_1   |
app_1   | == 20200316185531 AddDeviseGuestsToUsers: migrating ===========================
app_1   | -- change_table(:users)
app_1   |    -> 0.0133s
app_1   | == 20200316185531 AddDeviseGuestsToUsers: migrated (0.0137s) ==================
app_1   |
app_1   | [DEPRECATED] `Bundler.clean_system` has been deprecated in favor of `Bundler.unbundled_system`. If you instead want to run the command in the environment before bundler was originally loaded, use `Bundler.original_system` (called at /usr/local/bundle/gems/engine_cart-2.3.0/lib/engine_cart/tasks/engine_cart.rake:132)
app_1   | Done generating test app
blacklight_app_1 exited with code 0
```

🤔

**Comment by dkinzer** [comment]
@cdmo I'm not able to reproduce that issue locally.  Maybe it's caching issue.

Have you tried running?:

```
docker-compose up --build
```

or better yet

```
docker-compose up --build --force-recreate
```

**Comment by cdmo** [comment]
I ran `docker-compose up --build` and got the following: 

[docker-compose-build.log](https://github.com/projectblacklight/blacklight/files/4343529/docker-compose-build.log)

Looks like webpacker issues...

Same looking problems in the force option of compose up.

[docker-up-force.log](https://github.com/projectblacklight/blacklight/files/4343562/docker-up-force.log)

I'm not a docker expert, so I'm not able to diagnose. Plus there's the PR #2263 that maybe overlaps with this one? Should this PR get closed and we should just work off that one? Or are they orthogonal somehow and I'm missing the point?

**Comment by dkinzer** [comment]
Yup, that's fine.

**Pull request closed without merging**
