### PR TITLE
add in location_rpt field type and dynamic field prefix

### PR DESCRIPTION
**Pull request by mejackreed**
Not sure if we are still supporting < Solr 4. If we are then this PR should probably not be accepted.

### CODE REVIEW

**Comment by jcoyne** [comment]
I'm 👍 on dropping Solr 4 support.

**Comment by jkeck** [comment]
Should we ask the email list before we unilaterally drop support?

It seems like this field is an implementation detail that any application should/would be responsible for setting in their own solr configurations if they would like to take advantage of the behavior provided by this field.

I'm not necessarily advocating that we retain the solr4 support, but if the only thing preventing us from supporting it is a solr configuration that Blacklight itself isn't using, it seems like it may be a bit premature.

Just my $0.02, take it or leave it. :)

**Comment by cbeer** [comment]
👍  I think we're generating Solr 5+ into new applications.

**Comment by jkeck** [comment]
FWIW, it is possible to install Blacklight w/ solr4 (https://github.com/projectblacklight/blacklight/blob/master/lib/generators/blacklight/install_generator.rb#L30-L41) and was the default behavior (according the the installation documentation) as of Blacklight 6.0.

That means that Blacklight 6 adopters could update to a patch version that might actually break their application.

**Comment by cbeer** [comment]
> That means that Blacklight 6 adopters could update to a patch version that might actually break their application.

Only if you run a generator or rake task, though, right?

**Comment by jkeck** [comment]
@cbeer ah, fair point, and I suppose we don't really recommend running that generator or rake task as part of the update process.

Still, it seems to me like it would be a good idea to communicate that out before unilaterally dropping support (perhaps a simple email to the list indicating that we're dropping support would be sufficient).

I have a vague recollection of similar communications in the past when dropping support for particular major versions of our stack.

**Comment by jrochkind** [comment]
When i did my Blacklight community survey 6 months ago, 0 of 16 respondents were using Solr 3.x. (One was using 1.4 though! probably with an older version of BL). The vast majority were using Solr 4.x. 

I would expect dropping support for a version of Solr would occur on a major version BL release though.

**Comment by jrochkind** [comment]
Oh, I'm confused though -- the original comment here from @mejackreed  says "Not sure if we are still supporting < Solr 4. ", but then subsequent conversation is about dropping support for Solr 4? Did @mejackreed actually mean "<="?

Anyway, in my survey few were still using a Solr less than 4, but the vast majority were still using Solr 4.  To me this suggests it's probably time to drop support for solr _less than_ 4, but probably premature to drop support for 4.

**Comment by tampakis** [comment]
The way that the field is configured, the "distanceUnits" option wasn't available to version 5 of Solr.

**Comment by tampakis** [comment]
If users still wanted to install Solr 4, this [solrconfig.xml](https://github.com/projectblacklight/blacklight-jetty/blob/master/solr/blacklight-core/conf/solrconfig.xml) would be downloaded anyway right?

**Comment by mejackreed** [comment]
I would be happy to amend the commit to something similar to: https://github.com/projectblacklight/blacklight-jetty/commit/8381f9b6b003e2843386e5ab2166dfd2425425a8

As @tampakis pointed out, I think the main difference here is the `units` vs `distanceUnits` change which could remove Solr 4.x compatibility. The intent of this PR was not to introduce controversy on what versions of Solr to support. I'll look into `units` vs `distanceUnits` and see if there is something workable that would be compatible with both Solr 4.x and 5.x

**Comment by cbeer** [comment]
If it isn't easy, I'm 👍 to dropping Solr 4.x support, as it's 2 major versions behind.

**Comment by mejackreed** [comment]
Looking at things in Solr spatial dev stuff, there has been a lot of movement. So I'm less inclined to tying Blacklight core to that and having to maintain it. /shrug

**Pull request closed without merging**
