### PR TITLE
Test on Rails 5.1.0.rc2

### PR DESCRIPTION
**Pull request by jcoyne**

### CODE REVIEW

**Comment by cbeer** [comment]
I guess we need to chose between supporting Rails 4.2 and Rails 5.1, huh?

**Comment by jcoyne** [comment]
@cbeer if we want to take on a lot of work with converting our migrations to erb templates and sniffing for Rails versions, we could do both.  However, I think this is a good place to make a break from 4.2.

**Comment by jcoyne** [comment]
@cbeer here's the example of that https://github.com/plataformatec/devise/blob/master/lib/generators/active_record/templates/migration.rb#L1

**Comment by jcoyne** [comment]
Moved this work to #1579

**Pull request closed without merging**
