### PR TITLE
Change signature of SearchBuilder

### PR DESCRIPTION
**Pull request by jcoyne**

### CODE REVIEW

**Comment by jcoyne** [comment]
This should be rebased after #1702 is merged.

**Comment by jcoyne** [comment]
@cbeer I hear that, but I'm even less excited about having an object that looks like a Controller but is not, in order to use the SearchService.

Another approach is for the plugin to override `Catalog#search_service`. But then the plugin must have a custom subclass of SearchService, and of SearchBuilder.  That seems unnecessarily complex to me.

**Comment by jcoyne** [comment]
@cbeer how about creating a parameter object that encapsulates blacklight_config and may be subclassed to also hold `current_ability`?

**Comment by cbeer** [comment]
Fixed by #1646, probably?

**Comment by jcoyne** [comment]
@cbeer Uh, it's been a long time... probably?

**Pull request closed without merging**
