### PR TITLE
Pass controller instance to SearchState

### PR DESCRIPTION
**Pull request by jcoyne**
This allows subclasses to access the url_helpers

Alternative approach to #1645

### CODE REVIEW

**Comment by jeremyf** [comment]
@jcoyne What is the purpose of this change? Is it related to https://github.com/projectblacklight/blacklight/pull/1645

**Comment by jcoyne** [comment]
@jeremyf yes. @cbeer didn't seem thrilled with #1645 so this was proposed as an alternative.

**Comment by jeremyf** [comment]
I prefer this solution.

**Comment by atz** [comment]
Same, closing the other one.

**Comment by jcoyne** [comment]
Fixed #1639

**Pull request merged**
