### PR TITLE
Updates for Rails 5.0

### PR DESCRIPTION
**Pull request by jcoyne**

### CODE REVIEW

**Comment by cbeer** [comment]
:clap: I wonder how hard it'd be to keep support for Rails 4.1 -- if it's just `to_unsafe_h`, maybe we should check for it? Happy to ship it as-is, too.

**Comment by jcoyne** [comment]
Unfortunately Rails 5.0.0.beta1 is full of bugs, so I had to pin to edge.  I hope a second beta will be out in the next few weeks.  I'd like to hold off pushing out Blacklight 6 until we can say we support Rails 5.

It looks to me like Rails 4.1 doesn't have `AC::Parameters#to_unsafe_h`, so yeah, we could check for it, but I wonder if it makes sense to support a release of Rails that will be dropped from official support when Rails 5.0 goes out?

**Comment by jrochkind** [comment]
If you are going to drop support for 4.1, should you update the gemspec to no longer allow 4.1?

**Comment by jcoyne** [comment]
@jrochkind yeah, that would be prudent.

**Pull request merged**
