### PR TITLE
Removes Vagrantfile

### PR DESCRIPTION
**Pull request by cdmo**
This has been talked about a number of times, I'm proposing we remove the `Vagrantfile` which is old, outdated and unsupported.

### CODE REVIEW

**Comment by jronallo** [comment]
What's the current recommendation for getting set up as a developer for doing development on blacklight?

**Comment by mejackreed** [comment]
I've found that Go Rails usually covers everything we need https://gorails.com/setup . Maybe something like that is worth linking in the wiki?

**Comment by mejackreed** [comment]
@cdmo would you mind also 🔥 https://github.com/projectblacklight/blacklight/blob/master/provision.sh ?

**Comment by cdmo** [comment]
Great catch @mejackreed, thanks.

@jronallo I don't think there is a "current recommendation for getting set up as a developer for doing development on blacklight." Was there at one point? In #2231 this was brought up to some degree, but a full on: _if you are developing a feature for project blacklight use X_ doesn't seem to exist afaik.

**Comment by cdmo** [comment]
@mejackreed I updated the `.gitignore` too

**Pull request merged**
