### PR TITLE
Ensure that Blacklight is accessable globally

### LINKED ISSUE #2548: Can't call Blacklight.activate() on blacklight-frontend 7.21.1
It doesn't seem to define `window.Blacklight` as it once did. We could call it on 7.20.1

### PR DESCRIPTION
**Pull request by jcoyne**
Fixes #2548

### CODE REVIEW

**Comment by jrochkind** [comment]
Does this need to go into `main` branch too (or has it in a different PR/commit?), or it's enough to have it in release-7.x?

**Comment by jcoyne** [comment]
@jrochkind this only affects the 7.x branch.  main uses rollup instead, so it's a whole different strategy.

**Comment by jrochkind** [comment]
Oh okay, thanks!

I am only vaguely familiar with rollup. Does main branch/Blacklight 8 drop support for sprockets and webpacker then, it's been chosen to support only rollup (also as opposed to say `esbuild`?)

We don't necessarily have to talk about this here, but do you have any suggestions for how interested parties can keep up with what's going on (and perhaps ideally have input into it) related to choices of how JS will work for main/Blacklight 8?

**Comment by jcoyne** [comment]
@jrochkind no, we use rollup in blacklight to build the distribution.  You can use whatever you want in your app, sprockets, rollup, esbuild, `<script>` tags... Blacklight doesn't have an opinion.

**Comment by jrochkind** [comment]
Oh ok thanks. I'll have to figure out what that means as far as how to actually use the thing in BL 8/main at some point, I'm very confused.  But glad to hear the developers intent is to make it usable with sprockets and/or esbuild too.

**Pull request merged**
