### PR TITLE
Add Rails migration compatibility version to migrations

### LINKED ISSUE #1576: Deprecation: ActiveRecord::Migration inheritance
Warning on downstream builds against rails `5.0.0.1`, for example:

```
DEPRECATION WARNING: Directly inheriting from ActiveRecord::Migration is deprecated. 
Please specify the Rails release the migration was written for:
```
```ruby
  class CreateSearches < ActiveRecord::Migration[4.2]
```

Some examples start at: https://travis-ci.org/projectblacklight/blacklight_range_limit/builds/153589181#L711

### PR DESCRIPTION
**Pull request by cbeer**
Fixes #1576

### CODE REVIEW

**Comment by jcoyne** [comment]
This doesn't work for Rails 4. Shall we make it conditional, or drop support of Rails 4?

**Comment by cbeer** [comment]
Sorry, there's additional discussion on #1576.

**Comment by atz** [comment]
@jcoyne: you still approve this?  Seems like consensus was to shelve it until we drop rails 4.

**Comment by jcoyne** [comment]
@atz I'm okay with shelving.

**Comment by cbeer** [comment]
Rails 5.2 support, huh? That's a little ambitious.

**Comment by jcoyne** [comment]
I think it will work when devise is updated. I'll move that commit to a new branch tomorrow

**Pull request merged**
