### PR TITLE
Use solrwrapper for Solr 5.x

### PR DESCRIPTION
**Pull request by cbeer**

### CODE REVIEW

**Comment by jcoyne** [comment]
@cbeer  is this for Blacklight 5.10 or 6?

**Comment by cbeer** [comment]
6.x. There might be parts we could extract for 5.x though (like the spellcheck change)

**Comment by mejackreed** [comment]
:+1: :shipit: for 6?

**Comment by cbeer** [comment]
:+1:

**Comment by jrochkind** [comment]
Is BL6 going to require Solr 5, or still support 4 too?

**Comment by cbeer** [comment]
Solr 4 and 5 are pretty much API compatible as far as blacklight is concerned, so I imagine we'll support both. Even if they weren't, the index abstraction work provides a pattern for supporting other versions (e.g. if/when we start using Solr 4 features by default in here..)

**Pull request merged**
